[build]
publish = "docbuild/public"
command = "sh scripts/documentation-build.sh"

[build.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENABLEGITINFO = "true"

[context.production.environment]
HUGO_ENV = "production"

[[redirects]]
  from = "https://docs.postgres.rest/*"
  to = "https://docs.prestd.com/:splat"
  status = 301
  force = true
  headers = {X-From = "Netlify"}
